
# Identificadores de tu proyecto
sonar.projectKey=milodeskorpio
sonar.organization=Efrain Arcadio
sonar.projectName=web_page_timt_ri
sonar.projectVersion=1.0

# Dónde está el código fuente y qué carpetas ignorar
sonar.sources=src
sonar.exclusions=node_modules/**, dist/**, build/**