name: Security and Quality Pipeline

on:
  push:
    branches: ["main"]
permissions:
  issues: write
  pull-requests: write
  contents: read
jobs:
  # -------------------------------------------
  # PASO 1: SAST (Análisis Estático)
  # -------------------------------------------
  quality_and_sast:
    name: Code Quality and SAST (SonarQube)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run npm audit
        run: npm run security-check
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # -------------------------------------------
  # PASO 2: DAST LOCAL (Análisis Dinámico)
  # -------------------------------------------
  build_and_test_dast:
    name: Local Test and DAST (OWASP ZAP)
    needs: quality_and_sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Local Test Image
        run: docker build -t refactor_timt_app:test .

      - name: Run Local Container
        run: docker run -d -p 8080:8080 --name test-app refactor_timt_app:test

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@master
        with:
          target: "http://localhost:8080"
          fail_action: true
          cmd_options: "-I"

  # -------------------------------------------
  # PASO 3: EMPAQUETADO Y PUBLICACIÓN
  # -------------------------------------------
  publish_package:
    name: Build and Push Final Docker Image
    needs: build_and_test_dast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Aquí van los pasos para construir la imagen final

      - name: Build and Push
        run: echo "El código es 100% seguro. Subiendo imagen final a producción..."
